function UnlimitedPowerPriority:CreateVirtualCastButton()
    local vbtn = CreateFrame("Button", "UPP_VirtualCastButton", UIParent, "SecureActionButtonTemplate")
    vbtn:SetAttribute("type", "spell")
    vbtn:SetAttribute("spell", "Power Infusion")
    vbtn:SetScript("PostClick", function()
        C_Timer.After(0.1, function()
            UnlimitedPowerPriority:CastPowerInfusion()
        end)
    end)
end